# Generated by Django 5.0.2 on 2025-01-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_remove_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hire_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
