# Generated by Django 5.0.2 on 2025-01-23 07:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_user_hire_date_user_phone_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="phone_number",
            new_name="phone_no",
        ),
    ]
